version: '3.9'

services:

  flyway:
    container_name: flyway
    hostname: flyway
    image: flyway/flyway
    entrypoint: ["/flyway/flyway_commands.sh"]
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf:/flyway/conf
      - /Users/tilakkumar/Work/TurtleByte/root.crt:/root/.postgresql/root.crt
      - ./flyway/flyway_commands.sh:/flyway/flyway_commands.sh
    healthcheck:
      test: ["CMD-SHELL", "flyway", "info"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
